export enum AchievementId {
  StartingTrenches = 'starting_trenches',
  MouseOfBattlefield = 'mouse_of_battlefield',
  TreadingWater = 'treading_water',
  BrickhouseBoss = 'brickhouse_boss',
  MilitaryMaze = 'military_maze',
  BrushBattleground = 'brush_battleground',
  NewRevolution = 'new_revolution',
  DeathlessDriver1 = 'deathless_driver_1',
  DeathlessDriver2 = 'deathless_driver_2',
  ConfidentCommander1 = 'confident_commander_1',
  ConfidentCommander2 = 'confident_commander_2',
  CombatClear = 'combat_clear',
  StarSoldier = 'star_soldier',
  VacantBattlefield = 'vacant_battlefield',
  FullArsenal = 'full_arsenal',
  BattleBrigadier = 'battle_brigadier',
  CityChampion = 'city_champion',
}
