export enum GameSceneType {
  LevelControls,
  LevelLoad,
  LevelPlay,
  LevelScore,
  LevelSelection,
  MainAbout,
  MainGameOver,
  MainHighscore,
  MainMenu,
  MainVictory,
  ModesMenu,
  ModesCustom,
  SettingsAudio,
  SettingsInterface,
  SettingsKeybinding,
  SettingsMenu,
}
